### ISSUE TITLE
Bug Commit Thomas 

### ISSUE THREAD

**Issue by julhouss** [TetrisESIEA-TJM/CodeTetris#6]
L'adresse Ip est associée à la place du profile ...

**Comment by mohamad91** [comment]
> Invalid email This means the email address in your local Git configuration settings is either blank or not formatted as an email address. You will need to change the email address in your local Git configuration settings, then add the new address to your GitHub email settings to link your future commits. Old commits will not be linked.

[Permet de résoudre](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/)
